---
global:
  scrape_interval: "1s"
  evaluation_interval: "1s"

scrape_configs:
  - job_name: "spicedb"
    static_configs:
      - targets: ["spicedb-1:9090"]
        labels:
          service: "spicedb-1"
      - targets: ["spicedb-2:9090"]
        labels:
          service: "spicedb-2"
