---
name: "ClusterFuzzLite PR fuzzing"
on:
  push:
    branches:
      - "!dependabot/*"
      - "main"
  pull_request:
    branches: ["*"]
permissions: "read-all"
jobs:
  fuzz:
    runs-on: "ubuntu-latest"
    concurrency:
      group: "${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}"
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - "address"
          - "undefined"
          - "memory"
    steps:
      - name: "Build Fuzzers (${{ matrix.sanitizer }})"
        id: "build"
        uses: "google/clusterfuzzlite/actions/build_fuzzers@v1"
        with:
          language: "go"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          sanitizer: "${{ matrix.sanitizer }}"
      - name: "Run Fuzzers (${{ matrix.sanitizer }})"
        id: "run"
        uses: "google/clusterfuzzlite/actions/run_fuzzers@v1"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          fuzz-seconds: 30
          mode: "code-change"
          sanitizer: "${{ matrix.sanitizer }}"
