---
name: "Devel (nightly) Release"
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
permissions:
  contents: "read"
jobs:
  goreleaser:
    runs-on: "depot-ubuntu-24.04-4"
    permissions:
      contents: "write"
      packages: "write" # publish to GHCR
    steps:
      - uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v4.2.2
        with:
          fetch-depth: 0
      - uses: "authzed/actions/setup-go@882cac020050006e1829bd3cb1f90f4fe1b99cd6" # main
      - name: "Install snapcraft"
        run: |
          sudo snap install snapcraft --channel=8.x/stable --classic
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      - uses: "authzed/actions/docker-login@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
        with:
          quayio_token: "${{ secrets.QUAYIO_PASSWORD }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          dockerhub_token: "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}"
      - uses: "docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130" # v3.7.0
      - uses: "docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f" # v3.12.0
      - uses: "goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a" # v6.4.0
        with:
          distribution: "goreleaser-pro"
          version: "2.11.1"
          args: "release -f .goreleaser.nightly.yml --clean --nightly"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
